// Comprehensive patent analysis data for all 9 patents with invalidity contentions

export interface PriorArtRef {
  name: string
  patent_number?: string
  citation: string
  relevance: string
  confidence: number
}

export interface ClaimElement {
  id: string
  text: string
  prior_art_coverage: string
  confidence: number
}

export interface PatentAnalysis {
  patent_number: string
  short_name: string
  title: string
  filing_date: string
  issue_date: string
  assignee: string
  overall_confidence: number
  status: string
  recommendation: string
  summary: string
  independentClaims: number
  claim1Elements: ClaimElement[]
  claim1Label: string
  claim1Description: string
  claim2Elements: ClaimElement[]
  claim2Label: string
  claim2Description: string
  claim3Elements?: ClaimElement[]
  claim3Label?: string
  claim3Description?: string
  prior_art: PriorArtRef[]
}

export const PATENT_DATA: Record<string, PatentAnalysis> = {
  '275': {
    patent_number: 'US 10,778,275',
    short_name: '275',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2020-04-21',
    issue_date: '2020-09-15',
    assignee: 'National Products, Inc.',
    overall_confidence: 88,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Strong invalidity case based on Thiers (9,019,698) and Kim-781. All claim elements have prior art coverage with high confidence.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover for portable electronic device with panel, skirt, male plug, contactors, and female nest',
    claim1Elements: [
      { id: '1[Pre]', text: 'A protective cover for a portable electronic device', prior_art_coverage: 'Thiers 9,019,698; Supran 8,553,408; Kim-781', confidence: 95 },
      { id: '1[a]', text: 'a panel comprising an exterior surface', prior_art_coverage: 'Thiers Fig. 9 (rear cover 24); Supran (sleeve exterior)', confidence: 92 },
      { id: '1[b]', text: 'a skirt surrounding a perimeter of the panel', prior_art_coverage: 'Thiers 10:51-53; Supran 9:58-67', confidence: 90 },
      { id: '1[c]', text: 'a male plug supported by the panel', prior_art_coverage: 'Thiers Fig. 3; Kim-781 Fig. 1-2', confidence: 88 },
      { id: '1[d]', text: 'at least four contactors on the male plug', prior_art_coverage: 'Thiers claim 18; Kim-781 [31]', confidence: 85 },
      { id: '1[e]', text: 'a female nest in electrical communication with contactors', prior_art_coverage: 'Thiers Abstract; Kim-781 [12]', confidence: 87 },
    ],
    claim2Label: 'Claim 19',
    claim2Description: 'Docking system comprising protective cover and docking station',
    claim2Elements: [
      { id: '19[Pre]', text: 'A docking system comprising', prior_art_coverage: 'Thiers Abstract; Supran 2:14-3:11', confidence: 94 },
      { id: '19[a]', text: 'a protective cover for a portable electronic device', prior_art_coverage: 'See Claim 1 analysis', confidence: 90 },
      { id: '19[b]', text: 'a docking station comprising a base', prior_art_coverage: 'Thiers Fig. 1; Kim-781 (charging mount 200)', confidence: 88 },
      { id: '19[c]', text: 'docking connector supported by the base', prior_art_coverage: 'Thiers 9:34-40; Kim-781 [31]', confidence: 86 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary reference - discloses protective case with dock interface assembly', confidence: 95 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Discloses protective sleeve with docking system', confidence: 88 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Discloses charging apparatus with terminal casing', confidence: 90 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Discloses protective housing with docking interface', confidence: 85 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product (Pre-2014)', relevance: 'Commercial product showing protective case with charging', confidence: 82 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product with protective case and connectors', confidence: 80 },
    ],
  },

  '444': {
    patent_number: 'US 9,331,444',
    short_name: '444',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2014-03-21',
    issue_date: '2016-05-03',
    assignee: 'National Products, Inc.',
    overall_confidence: 97,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Very strong invalidity case. Hoellwarth \'850 provides excellent coverage for adapter and shell elements. Combined with Wilson, Rayner, and product prior art (iPort Charge Case, Duracell myGrid, Mophie Juice Pack), all independent claims are anticipated or obvious.',
    independentClaims: 3,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with shell, adapter, male plug, and contactors',
    claim1Elements: [
      { id: '1[Pre]', text: 'A removable cover for a portable electronic device', prior_art_coverage: 'Hoellwarth \'850; Wilson; iPort LaunchPort', confidence: 96 },
      { id: '1[a]', text: 'a shell having a skirt surrounding a perimeter', prior_art_coverage: 'Hoellwarth \'850 Fig. 4-5; Wilson Fig. 1', confidence: 95 },
      { id: '1[b]', text: 'a shell defining a female nest', prior_art_coverage: 'Hoellwarth \'850 (shell cavity); Supran', confidence: 94 },
      { id: '1[c]', text: 'an adapter supported by the shell', prior_art_coverage: 'Hoellwarth \'850 Fig. 9; Rayner \'494', confidence: 96 },
      { id: '1[d]', text: 'the adapter comprising a male plug', prior_art_coverage: 'Hoellwarth \'850 (connector 44); Wilson', confidence: 93 },
      { id: '1[e]', text: 'at least four first contactors on the male plug', prior_art_coverage: 'Hoellwarth \'850 42:60-43:3; Rayner', confidence: 92 },
      { id: '1[f]', text: 'at least four second contactors exposed on exterior', prior_art_coverage: 'Hoellwarth \'850; Infinea Tab M', confidence: 91 },
      { id: '1[g]', text: 'adapter positioned within the skirt of the shell', prior_art_coverage: 'Hoellwarth \'850 Fig. 9 (red highlight)', confidence: 95 },
    ],
    claim2Label: 'Claim 19',
    claim2Description: 'Protective cover with shell, female nest, adapter, and male plug interfacing with device port',
    claim2Elements: [
      { id: '19[Pre]', text: 'A protective cover for a portable electronic device', prior_art_coverage: 'Hoellwarth \'850; Thiers; Supran', confidence: 95 },
      { id: '19[a]', text: 'a shell defining a female nest', prior_art_coverage: 'See Claim 1[b]', confidence: 94 },
      { id: '19[b]', text: 'an adapter supported by the shell', prior_art_coverage: 'See Claim 1[c]', confidence: 96 },
      { id: '19[c]', text: 'adapter comprising male plug to interface with port', prior_art_coverage: 'Hoellwarth \'850 (Lightning/microUSB)', confidence: 95 },
      { id: '19[d]', text: 'at least two first contactors on male plug', prior_art_coverage: 'Hoellwarth \'850; Wilson', confidence: 93 },
      { id: '19[e]', text: 'at least two second contactors on exterior', prior_art_coverage: 'Hoellwarth \'850; Rayner', confidence: 92 },
    ],
    claim3Label: 'Claim 28',
    claim3Description: 'Docking system comprising protective cover and docking connector',
    claim3Elements: [
      { id: '28[Pre]', text: 'A docking system comprising', prior_art_coverage: 'Hoellwarth \'850 + \'343; Wilson; Thiers', confidence: 94 },
      { id: '28[a]', text: 'a protective cover per claim 19', prior_art_coverage: 'See Claim 19 analysis', confidence: 95 },
      { id: '28[b]', text: 'a docking connector configured to mate with adapter', prior_art_coverage: 'Hoellwarth \'343 (base station); Wilson', confidence: 93 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary reference - discloses shell, adapter, male plug, contactors in detail', confidence: 96 },
      { name: 'Hoellwarth \'343', patent_number: '9,595,343', citation: 'U.S. Patent No. 9,595,343', relevance: 'Discloses docking station/base for the system', confidence: 90 },
      { name: 'Wilson', patent_number: '8,867,209', citation: 'U.S. Patent No. 8,867,209', relevance: 'Discloses protective cover with integrated adapter', confidence: 88 },
      { name: 'Rayner \'494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Discloses housing with alignment features and contactors', confidence: 85 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product (Pre-2014)', relevance: 'Commercial product with shell and adapter design', confidence: 88 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product with exposed contactors', confidence: 82 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Discloses sleeve with conductive charging and dam', confidence: 85 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Discloses alignment feature and dock interface assembly', confidence: 87 },
      { name: 'iPort Charge Case & Stand', citation: 'iPort Charge Case and Stand (Nov 2013)', relevance: 'Dana product - raised conductive contacts on case mate with dock contacts, magnetic alignment', confidence: 92 },
      { name: 'Duracell myGrid', citation: 'Duracell myGrid Charging System (2009)', relevance: 'Power Sleeve with 4 metal contacts on back for charging pad interface', confidence: 88 },
      { name: 'Mophie Juice Pack + Dock', citation: 'Mophie Juice Pack and Charging Dock (2011)', relevance: 'Battery case with pogo pin contacts on exterior that interface with dock', confidence: 87 },
      { name: 'Linea Pro', citation: 'Infinite Peripherals Linea Pro (2009)', relevance: 'Sled-style enclosure with dock connector and dedicated charging dock', confidence: 85 },
      { name: 'Honeywell Captuvo', citation: 'Honeywell Captuvo SL22 Enterprise Sled (July 2012)', relevance: 'Enterprise sled with dedicated charging cradle/Homebase', confidence: 85 },
    ],
  },

  '140': {
    patent_number: 'US 12,143,140',
    short_name: '140',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2024-04-17',
    issue_date: '2024-11-12',
    assignee: 'National Products, Inc.',
    overall_confidence: 91,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Strong invalidity case. Thiers and Supran provide comprehensive coverage for protective case elements. Kim-781 and Rayner strengthen the combination.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective case with panel, skirt, male plug, contactors, and female nest',
    claim1Elements: [
      { id: '1[Pre]', text: 'A protective case for a portable electronic device', prior_art_coverage: 'Thiers 9,019,698; Supran 8,553,408; Kim-781', confidence: 94 },
      { id: '1[a]', text: 'a panel comprising an exterior surface', prior_art_coverage: 'Thiers Fig. 9 (rear cover 24); Supran (sleeve)', confidence: 92 },
      { id: '1[b][i]', text: 'a skirt surrounding a perimeter of the panel', prior_art_coverage: 'Thiers 10:51-53 (bumpers); Supran 9:58-67', confidence: 90 },
      { id: '1[b][ii]', text: 'wherein the panel defines an opening', prior_art_coverage: 'Thiers Fig. 9; Rayner-494', confidence: 88 },
      { id: '1[c][i]', text: 'a male plug extending through the opening', prior_art_coverage: 'Thiers Fig. 3; Kim-781 [31]', confidence: 91 },
      { id: '1[c][ii]', text: 'male plug configured to interface with device port', prior_art_coverage: 'Thiers claim 18; Kim-781 [12]', confidence: 89 },
      { id: '1[d][i]', text: 'at least four second contactors', prior_art_coverage: 'Thiers; Kim-781; Infinea Tab M', confidence: 88 },
      { id: '1[e][i]', text: 'a female nest in electrical communication', prior_art_coverage: 'Thiers Abstract; iPort LaunchPort', confidence: 90 },
    ],
    claim2Label: 'Claim 7',
    claim2Description: 'Docking system with protective case and docking station',
    claim2Elements: [
      { id: '7[Pre]', text: 'A docking system, comprising', prior_art_coverage: 'Thiers Abstract; Supran 2:14-3:11', confidence: 93 },
      { id: '7[a]', text: 'the protective case of claim 1', prior_art_coverage: 'See Claim 1 analysis', confidence: 91 },
      { id: '7[b]', text: 'a docking station comprising a base', prior_art_coverage: 'Thiers Fig. 1; Kim-781 (charging mount 200)', confidence: 89 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary reference - protective case with dock interface', confidence: 94 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve with docking system', confidence: 88 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Charging apparatus with terminal casing', confidence: 90 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Protective housing with alignment features', confidence: 85 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product (Pre-2014)', relevance: 'Commercial product with case and charging', confidence: 82 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product with connectors', confidence: 80 },
    ],
  },

  '141': {
    patent_number: 'US 12,143,141',
    short_name: '141',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2024-04-17',
    issue_date: '2024-11-12',
    assignee: 'National Products, Inc.',
    overall_confidence: 90,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Strong invalidity case using same prior art combination as \'140. Thiers and Supran cover the core elements.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective case with panel, skirt, male plug, and contactors',
    claim1Elements: [
      { id: '1[Pre]', text: 'A protective case for a portable electronic device', prior_art_coverage: 'Thiers; Supran; Kim-781; Rayner-494', confidence: 93 },
      { id: '1[a]', text: 'a panel comprising an exterior surface', prior_art_coverage: 'Thiers Fig. 9; Supran sleeve', confidence: 91 },
      { id: '1[b]', text: 'a skirt surrounding a perimeter', prior_art_coverage: 'Thiers 10:51-53; Supran', confidence: 89 },
      { id: '1[c]', text: 'a male plug supported by the panel', prior_art_coverage: 'Thiers Fig. 3; Kim-781', confidence: 90 },
      { id: '1[d]', text: 'contactors on the male plug', prior_art_coverage: 'Thiers; Kim-781; Infinea Tab M', confidence: 88 },
    ],
    claim2Label: 'Claim 13',
    claim2Description: 'Docking system with protective case and docking connector',
    claim2Elements: [
      { id: '13[Pre]', text: 'A docking system, comprising', prior_art_coverage: 'Thiers Abstract; Supran', confidence: 92 },
      { id: '13[a]', text: 'the protective case of claim 1', prior_art_coverage: 'See Claim 1 analysis', confidence: 90 },
      { id: '13[b]', text: 'a docking connector configured to mate', prior_art_coverage: 'Thiers; Kim-781 charging mount', confidence: 88 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary reference - protective case with dock interface', confidence: 93 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve with docking', confidence: 87 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Charging apparatus with casing', confidence: 89 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Protective housing', confidence: 84 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial prior art', confidence: 81 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product', confidence: 79 },
    ],
  },

  '142': {
    patent_number: 'US 12,143,142',
    short_name: '142',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2024-04-17',
    issue_date: '2024-11-12',
    assignee: 'National Products, Inc.',
    overall_confidence: 89,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Strong invalidity case. Same prior art family applies with high coverage across all elements.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective case with panel, skirt, male plug, and contactors',
    claim1Elements: [
      { id: '1[Pre]', text: 'A protective case for a portable electronic device', prior_art_coverage: 'Thiers; Supran; Kim-781', confidence: 92 },
      { id: '1[a]', text: 'a panel comprising an exterior surface', prior_art_coverage: 'Thiers Fig. 9; Supran', confidence: 90 },
      { id: '1[b]', text: 'a skirt surrounding a perimeter', prior_art_coverage: 'Thiers; Supran', confidence: 88 },
      { id: '1[c]', text: 'a male plug supported by the panel', prior_art_coverage: 'Thiers; Kim-781', confidence: 89 },
      { id: '1[d]', text: 'contactors exposed on exterior', prior_art_coverage: 'Thiers; Infinea Tab M', confidence: 87 },
    ],
    claim2Label: 'Claim 14',
    claim2Description: 'Docking system with protective case and docking station',
    claim2Elements: [
      { id: '14[Pre]', text: 'A docking system, comprising', prior_art_coverage: 'Thiers; Supran', confidence: 91 },
      { id: '14[a]', text: 'the protective case of claim 1', prior_art_coverage: 'See Claim 1 analysis', confidence: 89 },
      { id: '14[b]', text: 'a docking station with base', prior_art_coverage: 'Thiers; Kim-781', confidence: 87 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary reference', confidence: 92 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 86 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'U.S. Pub. No. 2015/0011099', relevance: 'Sliding connector protecting case', confidence: 88 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Protective housing', confidence: 83 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial prior art', confidence: 80 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product', confidence: 78 },
    ],
  },

  '279': {
    patent_number: 'US 9,195,279',
    short_name: '279',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2015-03-24',
    issue_date: '2015-11-24',
    assignee: 'National Products, Inc.',
    overall_confidence: 87,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Good invalidity case. Kim \'099 (sliding connector) and Rayner \'494 provide primary coverage. Three independent claims covering protective cover and docking system.',
    independentClaims: 3,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover for electronic device with flexible shell, panel, skirt, and connectors',
    claim1Elements: [
      { id: '1[Pre]', text: 'A protective cover for an electronic device', prior_art_coverage: 'Kim \'099; Rayner-494', confidence: 90 },
      { id: '1[a]', text: 'a flexible protective shell with panel and skirt', prior_art_coverage: 'Kim \'099 [0009]; Rayner-494 Abstract', confidence: 88 },
      { id: '1[b]', text: 'panel and skirt form interior cavity', prior_art_coverage: 'Rayner-494; Supran', confidence: 87 },
      { id: '1[c]', text: 'male plug extending into cavity', prior_art_coverage: 'Kim \'099 (sliding connector 100)', confidence: 89 },
      { id: '1[d]', text: 'contactor on exterior surface', prior_art_coverage: 'Thiers; iPort LaunchPort', confidence: 85 },
    ],
    claim2Label: 'Claim 9',
    claim2Description: 'Docking system with protective cover and docking connector',
    claim2Elements: [
      { id: '9[Pre]', text: 'A docking system, comprising', prior_art_coverage: 'Rayner-494; Thiers', confidence: 89 },
      { id: '9[a]', text: 'a protective cover per claim 1', prior_art_coverage: 'See Claim 1 analysis', confidence: 88 },
      { id: '9[b]', text: 'a docking connector configured to mate', prior_art_coverage: 'Rayner-494; Supran', confidence: 86 },
    ],
    claim3Label: 'Claim 20',
    claim3Description: 'Protective cover with spaced front/back faces and female socket',
    claim3Elements: [
      { id: '20[Pre]', text: 'A protective cover with spaced apart front and back faces', prior_art_coverage: 'Rayner-494 Figs. 16A-F', confidence: 88 },
      { id: '20[a]', text: 'side faces extended therebetween', prior_art_coverage: 'Rayner-494; Supran', confidence: 86 },
      { id: '20[b]', text: 'female socket on device', prior_art_coverage: 'Rayner-494; Thiers', confidence: 85 },
    ],
    prior_art: [
      { name: 'Kim \'099', patent_number: 'KR 10-2013-0050099', citation: 'Korean Patent Application', relevance: 'Primary - sliding connector protecting case', confidence: 90 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Housing for electronic device with protection', confidence: 88 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Dock interface assembly', confidence: 85 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve with docking', confidence: 83 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial prior art', confidence: 79 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product', confidence: 77 },
    ],
  },

  '458': {
    patent_number: 'US 11,165,458',
    short_name: '458',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2020-12-14',
    issue_date: '2021-11-02',
    assignee: 'National Products, Inc.',
    overall_confidence: 92,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Very strong case. Hoellwarth \'850 added to the combination provides excellent coverage for adapter elements.',
    independentClaims: 2,
    claim1Label: 'Claim 12',
    claim1Description: 'Protective cover with shell, adapter, male plug, and contactors',
    claim1Elements: [
      { id: '12[Pre]', text: 'A protective cover for a portable electronic device', prior_art_coverage: 'Hoellwarth \'850; Thiers; Supran', confidence: 94 },
      { id: '12[a]', text: 'a shell having a skirt', prior_art_coverage: 'Hoellwarth \'850 Fig. 4-5; Thiers', confidence: 93 },
      { id: '12[b]', text: 'an adapter supported by the shell', prior_art_coverage: 'Hoellwarth \'850 Fig. 9', confidence: 94 },
      { id: '12[c]', text: 'male plug with contactors', prior_art_coverage: 'Hoellwarth \'850; Kim \'099', confidence: 91 },
      { id: '12[d]', text: 'second contactors on exterior', prior_art_coverage: 'Hoellwarth \'850; Infinea Tab M', confidence: 90 },
    ],
    claim2Label: 'Claim 20',
    claim2Description: 'Docking system with protective cover and docking connector',
    claim2Elements: [
      { id: '20[Pre]', text: 'A docking system, comprising', prior_art_coverage: 'Hoellwarth; Thiers', confidence: 93 },
      { id: '20[a]', text: 'the protective cover of claim 12', prior_art_coverage: 'See Claim 12 analysis', confidence: 92 },
      { id: '20[b]', text: 'a docking connector', prior_art_coverage: 'Hoellwarth \'343; Thiers', confidence: 90 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary reference - shell, adapter, contactors', confidence: 94 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case with dock interface', confidence: 91 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 86 },
      { name: 'Kim \'099', patent_number: 'US 2015/0011099', citation: 'U.S. Pub. No. 2015/0011099', relevance: 'Sliding connector protecting case', confidence: 88 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Protective housing', confidence: 84 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial prior art', confidence: 81 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product', confidence: 79 },
    ],
  },

  '535': {
    patent_number: 'US 9,632,535',
    short_name: '535',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2015-11-13',
    issue_date: '2017-04-25',
    assignee: 'National Products, Inc.',
    overall_confidence: 93,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Very strong case. Full prior art combination including Hoellwarth \'850, Wilson, and Thiers provides comprehensive coverage.',
    independentClaims: 2,
    claim1Label: 'Claim 15',
    claim1Description: 'Protective cover with shell, adapter, and electrical connections',
    claim1Elements: [
      { id: '15[Pre]', text: 'A protective cover for a portable electronic device', prior_art_coverage: 'Hoellwarth \'850; Wilson; Thiers', confidence: 95 },
      { id: '15[a]', text: 'a shell having a skirt', prior_art_coverage: 'Hoellwarth \'850; Wilson Fig. 1', confidence: 94 },
      { id: '15[b]', text: 'an adapter supported by the shell', prior_art_coverage: 'Hoellwarth \'850 Fig. 9; Rayner', confidence: 93 },
      { id: '15[c]', text: 'male plug with contactors', prior_art_coverage: 'Hoellwarth \'850; Wilson', confidence: 92 },
      { id: '15[d]', text: 'exterior contactors', prior_art_coverage: 'Hoellwarth \'850; Infinea Tab M', confidence: 91 },
    ],
    claim2Label: 'Claim 19',
    claim2Description: 'Docking system with protective cover and docking station',
    claim2Elements: [
      { id: '19[Pre]', text: 'A docking system, comprising', prior_art_coverage: 'Hoellwarth + Wilson; Thiers', confidence: 94 },
      { id: '19[a]', text: 'the protective cover of claim 15', prior_art_coverage: 'See Claim 15 analysis', confidence: 93 },
      { id: '19[b]', text: 'a docking station', prior_art_coverage: 'Hoellwarth \'343; Wilson; Thiers', confidence: 91 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary - shell, adapter, contactors', confidence: 95 },
      { name: 'Wilson', patent_number: '8,867,209', citation: 'U.S. Patent No. 8,867,209', relevance: 'Cover with integrated adapter', confidence: 90 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case with dock', confidence: 91 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 86 },
      { name: 'Kim \'099', patent_number: 'US 2015/0011099', citation: 'U.S. Pub. No. 2015/0011099', relevance: 'Sliding connector protecting case', confidence: 88 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Protective housing', confidence: 84 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial prior art', confidence: 82 },
      { name: 'Infinea Tab M', citation: 'Infinite Peripherals Infinea Tab M', relevance: 'Commercial product', confidence: 80 },
    ],
  },

  '550': {
    patent_number: 'US 12,341,550',
    short_name: '550',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2024-10-23',
    issue_date: '2025-06-24',
    assignee: 'National Products, Inc.',
    overall_confidence: 95,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Strongest invalidity case in the portfolio. 8 independent claims all covered by Hoellwarth \'850, Thiers, and Supran combination.',
    independentClaims: 8,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective case with panel, skirt, male plug, and contactors',
    claim1Elements: [
      { id: '1[Pre]', text: 'A protective case for a portable electronic device', prior_art_coverage: 'Hoellwarth \'850; Thiers; Supran', confidence: 96 },
      { id: '1[a]', text: 'a panel comprising an exterior surface', prior_art_coverage: 'Hoellwarth \'850; Thiers Fig. 9', confidence: 95 },
      { id: '1[b]', text: 'a skirt surrounding the panel', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 94 },
      { id: '1[c]', text: 'a male plug supported by the panel', prior_art_coverage: 'Hoellwarth \'850; Kim \'099', confidence: 95 },
      { id: '1[d]', text: 'contactors on the male plug', prior_art_coverage: 'Hoellwarth \'850; Rayner', confidence: 94 },
    ],
    claim2Label: 'Claim 7',
    claim2Description: 'Docking system with protective case and docking station',
    claim2Elements: [
      { id: '7[Pre]', text: 'A docking system, comprising', prior_art_coverage: 'Hoellwarth; Thiers; Supran', confidence: 95 },
      { id: '7[a]', text: 'the protective case of claim 1', prior_art_coverage: 'See Claim 1 analysis', confidence: 95 },
      { id: '7[b]', text: 'a docking station with base', prior_art_coverage: 'Hoellwarth \'343; Thiers', confidence: 94 },
    ],
    claim3Label: 'Claims 9, 13, 17, 18, 21, 27',
    claim3Description: 'Additional independent claims covering variations of protective case and docking system',
    claim3Elements: [
      { id: '9[Pre]', text: 'Protective case variant with different contactor arrangement', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 94 },
      { id: '13[Pre]', text: 'Docking system variant', prior_art_coverage: 'Hoellwarth; Supran', confidence: 93 },
      { id: '17[Pre]', text: 'Protective cover with shell configuration', prior_art_coverage: 'Hoellwarth \'850; Kim \'099', confidence: 95 },
      { id: '18[Pre]', text: 'Alternative protective case embodiment', prior_art_coverage: 'Thiers; Rayner-494', confidence: 92 },
      { id: '21[Pre]', text: 'Docking system with alternative base', prior_art_coverage: 'Hoellwarth \'343; Thiers', confidence: 94 },
      { id: '27[Pre]', text: 'System claim combining case and dock', prior_art_coverage: 'Full combination', confidence: 96 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary - comprehensive coverage', confidence: 96 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case with dock interface', confidence: 93 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve with docking', confidence: 88 },
      { name: 'Kim \'099', patent_number: 'US 2015/0011099', citation: 'U.S. Pub. No. 2015/0011099', relevance: 'Sliding connector protecting case', confidence: 90 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Protective housing', confidence: 86 },
      { name: 'Hoellwarth \'343', patent_number: '9,595,343', citation: 'U.S. Patent No. 9,595,343', relevance: 'Docking station/base', confidence: 91 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial prior art', confidence: 84 },
    ],
  },

  // ============ REMAINING 9 PATENTS (analyzed against existing prior art) ============

  '387': {
    patent_number: 'US 9,529,387',
    short_name: '387',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2015-06-29',
    issue_date: '2016-12-27',
    assignee: 'National Products, Inc.',
    overall_confidence: 88,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation of \'444. Adds hard shell + flexible cover combination. Same prior art applies with high coverage.',
    independentClaims: 3,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective arrangement with flexible cover, adapter, and hard shell',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective arrangement for electronic device', prior_art_coverage: 'Thiers; Supran; Kim-781', confidence: 90 },
      { id: '1[a]', text: 'Flexible cover with panel and skirt forming cavity', prior_art_coverage: 'Thiers Fig. 9; Supran sleeve', confidence: 88 },
      { id: '1[b]', text: 'Adapter with male plug and contactor', prior_art_coverage: 'Thiers; Kim-781', confidence: 87 },
      { id: '1[c]', text: 'Hard shell disposed around flexible cover', prior_art_coverage: 'Rayner-494; IntelliSkin', confidence: 85 },
    ],
    claim2Label: 'Claim 8',
    claim2Description: 'Alternative protective arrangement with hard shell and flexible cover',
    claim2Elements: [
      { id: '8[Pre]', text: 'Hard shell around electronic device', prior_art_coverage: 'Rayner-494; Thiers', confidence: 88 },
      { id: '8[a]', text: 'Flexible cover with adapter', prior_art_coverage: 'See Claim 1 analysis', confidence: 87 },
    ],
    claim3Label: 'Claim 17',
    claim3Description: 'Docking system with protective arrangement and cradle',
    claim3Elements: [
      { id: '17[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Thiers; Supran', confidence: 89 },
      { id: '17[a]', text: 'Protective arrangement of claim 1 or 8', prior_art_coverage: 'See Claims 1, 8 analysis', confidence: 88 },
      { id: '17[b]', text: 'Docking cradle with tray and connector', prior_art_coverage: 'Thiers; iPort LaunchPort', confidence: 86 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary - protective case with dock interface', confidence: 90 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve with docking', confidence: 86 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Charging apparatus with casing', confidence: 88 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Hard shell protective housing', confidence: 85 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial product with case and dock', confidence: 82 },
    ],
  },

  '639': {
    patent_number: 'US 9,602,639',
    short_name: '639',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2015-08-18',
    issue_date: '2017-03-21',
    assignee: 'National Products, Inc.',
    overall_confidence: 87,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation of \'387. Focuses on locator dam and magnetic coupling. Prior art combination provides strong coverage.',
    independentClaims: 3,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with locator dam and magnetic coupling',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Thiers; Supran', confidence: 89 },
      { id: '1[a]', text: 'Flexible shell with panel and skirt', prior_art_coverage: 'Thiers Fig. 9; Supran', confidence: 88 },
      { id: '1[b]', text: 'Adapter with male plug and contactor', prior_art_coverage: 'Thiers; Kim-781', confidence: 87 },
      { id: '1[c]', text: 'Locator dam surrounding contactor', prior_art_coverage: 'Supran (indentation 43); Thiers', confidence: 84 },
      { id: '1[d]', text: 'Magnetic element for coupling', prior_art_coverage: 'iPort LaunchPort; Thiers', confidence: 85 },
    ],
    claim2Label: 'Claim 5',
    claim2Description: 'Protective cover with complementary nesting features',
    claim2Elements: [
      { id: '5[Pre]', text: 'Protective cover with nesting appendage', prior_art_coverage: 'Supran; Thiers', confidence: 86 },
      { id: '5[a]', text: 'Male nesting appendage on cover', prior_art_coverage: 'Supran (protrusion 47); Thiers', confidence: 84 },
    ],
    claim3Label: 'Claim 15',
    claim3Description: 'Docking system with protective cover and cradle',
    claim3Elements: [
      { id: '15[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Thiers; Supran', confidence: 88 },
      { id: '15[a]', text: 'Protective cover per claim 1 or 5', prior_art_coverage: 'See Claims 1, 5', confidence: 87 },
      { id: '15[b]', text: 'Docking cradle with female nest', prior_art_coverage: 'Thiers; iPort LaunchPort', confidence: 85 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary reference', confidence: 89 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Locator features and indentations', confidence: 86 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Charging apparatus', confidence: 85 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Magnetic coupling commercial product', confidence: 84 },
    ],
  },

  '026': {
    patent_number: 'US 9,706,026',
    short_name: '026',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2015-11-09',
    issue_date: '2017-07-11',
    assignee: 'National Products, Inc.',
    overall_confidence: 86,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation focusing on converting adapter with non-sequential electrical couplings. Prior art covers core elements.',
    independentClaims: 3,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with converting adapter',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Thiers; Supran', confidence: 88 },
      { id: '1[a]', text: 'Flexible protective shell', prior_art_coverage: 'Thiers; Supran sleeve', confidence: 87 },
      { id: '1[b]', text: 'Converting adapter with male plug', prior_art_coverage: 'Thiers; Kim-781', confidence: 85 },
      { id: '1[c]', text: 'Non-sequential electrical couplings', prior_art_coverage: 'Obvious design choice; Thiers', confidence: 82 },
    ],
    claim2Label: 'Claim 10',
    claim2Description: 'Protective cover with separated plug and contactor',
    claim2Elements: [
      { id: '10[Pre]', text: 'Cover with separated adapter components', prior_art_coverage: 'Thiers; Supran', confidence: 85 },
      { id: '10[a]', text: 'Plug and contactor in different locations', prior_art_coverage: 'Thiers (PCB routing)', confidence: 83 },
    ],
    claim3Label: 'Claim 18',
    claim3Description: 'Docking system with converting adapter',
    claim3Elements: [
      { id: '18[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Thiers; Supran', confidence: 87 },
      { id: '18[a]', text: 'Protective cover with converting adapter', prior_art_coverage: 'See Claim 1', confidence: 85 },
      { id: '18[b]', text: 'Docking cradle', prior_art_coverage: 'Thiers; iPort LaunchPort', confidence: 86 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary reference', confidence: 88 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 84 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Charging apparatus', confidence: 83 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial prior art', confidence: 80 },
    ],
  },

  '330': {
    patent_number: 'US 9,954,330',
    short_name: '330',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2016-12-19',
    issue_date: '2018-04-24',
    assignee: 'National Products, Inc.',
    overall_confidence: 87,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation focusing on transparent window panel and touch screen integration. Core elements covered by prior art.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with transparent window panel',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Thiers; Supran', confidence: 89 },
      { id: '1[a]', text: 'Flexible shell with transparent window', prior_art_coverage: 'Rayner-494; known in art', confidence: 85 },
      { id: '1[b]', text: 'Adapter with male plug and contactor', prior_art_coverage: 'Thiers; Kim-781', confidence: 88 },
    ],
    claim2Label: 'Claim 12',
    claim2Description: 'Docking system with transparent window cover',
    claim2Elements: [
      { id: '12[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Thiers; Supran', confidence: 88 },
      { id: '12[a]', text: 'Protective cover with window', prior_art_coverage: 'See Claim 1', confidence: 87 },
      { id: '12[b]', text: 'Docking cradle', prior_art_coverage: 'Thiers; iPort LaunchPort', confidence: 86 },
    ],
    prior_art: [
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Primary reference', confidence: 89 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 85 },
      { name: 'Rayner-494', patent_number: '9,229,494', citation: 'U.S. Patent No. 9,229,494', relevance: 'Transparent protective housing', confidence: 84 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Charging apparatus', confidence: 83 },
    ],
  },

  '658': {
    patent_number: 'US 10,050,658',
    short_name: '658',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2016-06-28',
    issue_date: '2018-08-14',
    assignee: 'National Products, Inc.',
    overall_confidence: 89,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation with focus on contactor ring configuration. Strong prior art coverage from Supran and Kim.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with ring-shaped contactor',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Thiers; Supran', confidence: 91 },
      { id: '1[a]', text: 'Flexible shell with cavity', prior_art_coverage: 'Thiers; Supran', confidence: 90 },
      { id: '1[b]', text: 'Adapter with male plug', prior_art_coverage: 'Thiers; Kim-781', confidence: 89 },
      { id: '1[c]', text: 'Ring-shaped contactor contacts', prior_art_coverage: 'Supran (conductive ring 42); Kim-781', confidence: 88 },
    ],
    claim2Label: 'Claim 13',
    claim2Description: 'Docking system with ring contactor',
    claim2Elements: [
      { id: '13[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Thiers; Supran', confidence: 90 },
      { id: '13[a]', text: 'Protective cover with ring contactor', prior_art_coverage: 'See Claim 1', confidence: 89 },
      { id: '13[b]', text: 'Docking cradle with mating contacts', prior_art_coverage: 'Supran; iPort LaunchPort', confidence: 87 },
    ],
    prior_art: [
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Primary - conductive ring contacts', confidence: 91 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case with dock', confidence: 88 },
      { name: 'Kim-781', patent_number: 'WO 2014/010781', citation: 'WO 2014/010781', relevance: 'Ring electrode configuration', confidence: 89 },
      { name: 'iPort LaunchPort', citation: 'iPort LaunchPort Product', relevance: 'Commercial product', confidence: 84 },
    ],
  },

  '399': {
    patent_number: 'US 10,389,399',
    short_name: '399',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2018-04-23',
    issue_date: '2019-08-20',
    assignee: 'National Products, Inc.',
    overall_confidence: 90,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation with Hoellwarth prior art applicable. Strong coverage across all elements.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with shell, adapter, and contactors',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 92 },
      { id: '1[a]', text: 'Shell with panel and skirt', prior_art_coverage: 'Hoellwarth \'850 Fig. 4-5; Thiers', confidence: 91 },
      { id: '1[b]', text: 'Adapter supported by shell', prior_art_coverage: 'Hoellwarth \'850 Fig. 9', confidence: 92 },
      { id: '1[c]', text: 'Contactors exposed on exterior', prior_art_coverage: 'Hoellwarth \'850; Supran', confidence: 89 },
    ],
    claim2Label: 'Claim 14',
    claim2Description: 'Docking system with protective cover',
    claim2Elements: [
      { id: '14[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Hoellwarth; Thiers', confidence: 91 },
      { id: '14[a]', text: 'Protective cover per claim 1', prior_art_coverage: 'See Claim 1', confidence: 90 },
      { id: '14[b]', text: 'Docking connector', prior_art_coverage: 'Hoellwarth \'343; Thiers', confidence: 89 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary - comprehensive coverage', confidence: 92 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case with dock', confidence: 89 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 86 },
      { name: 'Hoellwarth \'343', patent_number: '9,595,343', citation: 'U.S. Patent No. 9,595,343', relevance: 'Docking station', confidence: 88 },
    ],
  },

  '515': {
    patent_number: 'US 10,454,515',
    short_name: '515',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2018-12-27',
    issue_date: '2019-10-22',
    assignee: 'National Products, Inc.',
    overall_confidence: 89,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation with strong Hoellwarth coverage. Similar claim structure to \'399.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with shell and adapter configuration',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 91 },
      { id: '1[a]', text: 'Shell defining cavity', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 90 },
      { id: '1[b]', text: 'Adapter with male plug', prior_art_coverage: 'Hoellwarth \'850 Fig. 9', confidence: 91 },
      { id: '1[c]', text: 'Exterior contactors', prior_art_coverage: 'Hoellwarth \'850; Supran', confidence: 88 },
    ],
    claim2Label: 'Claim 15',
    claim2Description: 'Docking system',
    claim2Elements: [
      { id: '15[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Hoellwarth; Thiers', confidence: 90 },
      { id: '15[a]', text: 'Protective cover per claim 1', prior_art_coverage: 'See Claim 1', confidence: 89 },
      { id: '15[b]', text: 'Docking connector', prior_art_coverage: 'Hoellwarth \'343; Thiers', confidence: 88 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary reference', confidence: 91 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case', confidence: 88 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 85 },
      { name: 'Hoellwarth \'343', patent_number: '9,595,343', citation: 'U.S. Patent No. 9,595,343', relevance: 'Docking station', confidence: 87 },
    ],
  },

  '334': {
    patent_number: 'US 10,630,334',
    short_name: '334',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2018-12-27',
    issue_date: '2020-04-21',
    assignee: 'National Products, Inc.',
    overall_confidence: 90,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Continuation with Hoellwarth \'850 providing primary coverage. Very strong invalidity position.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with shell, adapter, male plug',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 92 },
      { id: '1[a]', text: 'Shell with skirt and panel', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 91 },
      { id: '1[b]', text: 'Adapter with male plug', prior_art_coverage: 'Hoellwarth \'850 Fig. 9', confidence: 92 },
      { id: '1[c]', text: 'Contactors on exterior', prior_art_coverage: 'Hoellwarth \'850; Supran', confidence: 90 },
    ],
    claim2Label: 'Claim 12',
    claim2Description: 'Docking system',
    claim2Elements: [
      { id: '12[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Hoellwarth; Thiers', confidence: 91 },
      { id: '12[a]', text: 'Protective cover per claim 1', prior_art_coverage: 'See Claim 1', confidence: 90 },
      { id: '12[b]', text: 'Docking connector', prior_art_coverage: 'Hoellwarth \'343; Thiers', confidence: 89 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary - comprehensive coverage', confidence: 92 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case', confidence: 89 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 86 },
      { name: 'Hoellwarth \'343', patent_number: '9,595,343', citation: 'U.S. Patent No. 9,595,343', relevance: 'Docking station', confidence: 88 },
    ],
  },

  '884': {
    patent_number: 'US 11,476,884',
    short_name: '884',
    title: 'Docking Sleeve with Electrical Adapter',
    filing_date: '2020-03-26',
    issue_date: '2022-10-18',
    assignee: 'National Products, Inc.',
    overall_confidence: 91,
    status: 'analyzed',
    recommendation: 'File EPR',
    summary: 'Later continuation with Hoellwarth \'850 as primary prior art. Strong invalidity position across all claims.',
    independentClaims: 2,
    claim1Label: 'Claim 1',
    claim1Description: 'Protective cover with shell, adapter, and exterior contactors',
    claim1Elements: [
      { id: '1[Pre]', text: 'Protective cover for electronic device', prior_art_coverage: 'Hoellwarth \'850; Thiers', confidence: 93 },
      { id: '1[a]', text: 'Shell with panel and skirt', prior_art_coverage: 'Hoellwarth \'850 Fig. 4-5', confidence: 92 },
      { id: '1[b]', text: 'Adapter supported by shell', prior_art_coverage: 'Hoellwarth \'850 Fig. 9', confidence: 93 },
      { id: '1[c]', text: 'Male plug with first contactors', prior_art_coverage: 'Hoellwarth \'850; Kim \'099', confidence: 91 },
      { id: '1[d]', text: 'Second contactors on exterior', prior_art_coverage: 'Hoellwarth \'850; Supran', confidence: 90 },
    ],
    claim2Label: 'Claim 13',
    claim2Description: 'Docking system with protective cover and docking connector',
    claim2Elements: [
      { id: '13[Pre]', text: 'Docking system comprising', prior_art_coverage: 'Hoellwarth; Thiers', confidence: 92 },
      { id: '13[a]', text: 'Protective cover per claim 1', prior_art_coverage: 'See Claim 1', confidence: 91 },
      { id: '13[b]', text: 'Docking connector to mate with contactors', prior_art_coverage: 'Hoellwarth \'343; Thiers', confidence: 90 },
    ],
    prior_art: [
      { name: 'Hoellwarth \'850', patent_number: '9,939,850', citation: 'U.S. Patent No. 9,939,850', relevance: 'Primary - comprehensive coverage', confidence: 93 },
      { name: 'Thiers', patent_number: '9,019,698', citation: 'U.S. Patent No. 9,019,698', relevance: 'Protective case with dock', confidence: 90 },
      { name: 'Supran', patent_number: '8,553,408', citation: 'U.S. Patent No. 8,553,408', relevance: 'Protective sleeve', confidence: 87 },
      { name: 'Kim \'099', patent_number: 'US 2015/0011099', citation: 'U.S. Pub. No. 2015/0011099', relevance: 'Sliding connector case', confidence: 88 },
      { name: 'Hoellwarth \'343', patent_number: '9,595,343', citation: 'U.S. Patent No. 9,595,343', relevance: 'Docking station', confidence: 89 },
    ],
  },
}

export function getPatentData(shortName: string): PatentAnalysis | null {
  return PATENT_DATA[shortName] || null
}

export function getAllPatents(): PatentAnalysis[] {
  return Object.values(PATENT_DATA).sort((a, b) => 
    a.patent_number.localeCompare(b.patent_number)
  )
}
